/*  jtdeco16ic_mmr.v was generated by jtframe mmr.
    Do not edit this generated file directly.
    Edit cfg/mmr.yaml or modules/jtframe/hdl/inc/mmr.v instead.
    Do not add generated *_mmr.v files to git. */

module jtdeco16ic_mmr(
    input             rst,
    input             clk,

    input             cs,
    input       [3:1] addr,
    input             rnw,
    input       [15:0] din, 
    input       [1:0] dsn,
    
    output [15:0] pf1_scrollx,
    output [15:0] pf1_scrolly,
    output [15:0] pf2_scrollx,
    output [15:0] pf2_scrolly,
    output [7:0] pf1_ctrl0,
    output [7:0] pf2_ctrl0,
    output [7:0] pf1_ctrl1,
    output [7:0] pf2_ctrl1,
    output [15:0] bank_ctl,

    // IOCTL dump
    input      [3:0] ioctl_addr,
    output reg [7:0] ioctl_din,
    // Debug
    input      [7:0] debug_bus,
    output reg [7:0] st_dout
);

localparam SIZE=16;
parameter SIMFILE="rest.bin",
          SEEK=0;
parameter [SIZE*8-1:0] INIT=0; // from high to low regs {mmr[3],mmr[2],mmr[1],mmr[0]}


reg  [ 7:0] mmr[0:SIZE-1];
integer     i;
`ifdef SIMULATION
reg [7:0] mmr_init[0:SIZE-1];
`endif

assign pf1_scrollx = {
    mmr[3][7:0],
    mmr[2][7:0]
    };

assign pf1_scrolly = {
    mmr[5][7:0],
    mmr[4][7:0]
    };

assign pf2_scrollx = {
    mmr[7][7:0],
    mmr[6][7:0]
    };

assign pf2_scrolly = {
    mmr[9][7:0],
    mmr[8][7:0]
    };

assign pf1_ctrl0 = {
    mmr[10][7:0]
    };

assign pf2_ctrl0 = {
    mmr[11][7:0]
    };

assign pf1_ctrl1 = {
    mmr[12][7:0]
    };

assign pf2_ctrl1 = {
    mmr[13][7:0]
    };

assign bank_ctl = {
    mmr[15][7:0],
    mmr[14][7:0]
    };


always @(posedge clk) begin
    if( rst ) begin
    `ifndef SIMULATION
        for(i=0;i<SIZE;i=i+1) mmr[i] <= INIT[i*8+:8];
    `else
        for(i=0;i<SIZE;i=i+1) mmr[i] <= mmr_init[i];
    `endif 
    end else begin
        st_dout   <= mmr[debug_bus[3:0]];
        ioctl_din <= mmr[ioctl_addr];
        if( cs & ~rnw ) begin
            if(!dsn[0]) mmr[{addr,1'b0}]<=din[ 7:0];
            if(!dsn[1]) mmr[{addr,1'b1}]<=din[15:8];
        end
        i = 0; // for Quartus linter
    end
end

`ifdef SIMULATION
/* verilator tracing_off */
integer f, fcnt, err;
initial begin
    f=$fopen(SIMFILE,"rb");
    err=$fseek(f,SEEK,0);
    if( f!=0 && err!=0 ) begin
        $display("Cannot seek file rest.bin to offset 0x%0X (%0d)",SEEK,SEEK);
    end
    if( f!=0 ) begin
        fcnt=$fread(mmr_init,f);
        $display("MMR %m - read %0d bytes from offset %0d",fcnt,SEEK);
        if( fcnt!=SIZE ) begin
            $display("WARNING: Missing %d bytes for %m.mmr",SIZE-fcnt);
        end else begin
            $display("\tpf1_scrollx = %X",{ mmr_init[3][7:0], mmr_init[2][7:0] });
            $display("\tpf1_scrolly = %X",{ mmr_init[5][7:0], mmr_init[4][7:0] });
            $display("\tpf2_scrollx = %X",{ mmr_init[7][7:0], mmr_init[6][7:0] });
            $display("\tpf2_scrolly = %X",{ mmr_init[9][7:0], mmr_init[8][7:0] });
            $display("\tpf1_ctrl0 = %X",{ mmr_init[10][7:0] });
            $display("\tpf2_ctrl0 = %X",{ mmr_init[11][7:0] });
            $display("\tpf1_ctrl1 = %X",{ mmr_init[12][7:0] });
            $display("\tpf2_ctrl1 = %X",{ mmr_init[13][7:0] });
            $display("\tbank_ctl = %X",{ mmr_init[15][7:0], mmr_init[14][7:0] });
        end
    end else begin
        for(i=0;i<SIZE;i=i+1) mmr_init[i] = 0;
    end
    $fclose(f);
end
`endif

endmodule
